
const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}

module.exports = {
SESSION_ID: process.env.SESSION_ID || "starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUVEamZ3Y08vdUZWTGR4bkJib2MvM0hVRE1lM1dkVDk0NjBxTC9tVWRtMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicmtPZisxcVdoc1Z6Zzl3K1dqWUlEQTIzTVE2SWNOSnhaQnd6SFZLZ0N5Yz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnQUUzWFhIREpQTHZyelhiam5mOVVEUEdGNTl2WkNWZjJSOXVXYkhmUW04PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCNmxDelRhbnBhWW9wWDFPN2dXRXJqM1Y5bU9oS2VGYWFzMWs0TVlOREFBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdIcndKRC93OS83WjVYb2prdDh0blVKMnlWVDNlTDcxekFIRUxVdXk3MkE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im0xSFFUN2VBRWJ6dXpDYmVHczZ6Qm5xQXBYS28vR1FBU01nK2lQUGQ3bUU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0U4R1R3RXRMZUFZM0NpVXV5b2ZGQktodVZpRVUycWwxcEtxS1hKb1FIRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0V3VG9WUmMzVEhKbUR6a2lCeGhWekFBdDcvWG1WdWdGNmRQUjFYbWlBWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik43ZjVYemlSMS93c2krZGF4SVpWODNWQmt6TUE3VWNXNjZja0VIZk1pUHdaN2FKNVUxNlJaVk92LzAxTEQ5V20zOVRrLzJUYThMUUQwQ2VydHoybUJBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTEsImFkdlNlY3JldEtleSI6ImdDczhFSUg2ajFLVzRBbjRkTmoxVTdEUHBCMjN4dmZoNjYvcERyRmhua289IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjI2NjE0NDA5MzRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQUMzNTdFMzBFNTMyODk2QzE1MjFFMUNDNkZGMjZBNDgifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc2NzgwMzk2NX1dLCJuZXh0UHJlS2V5SWQiOjE2MjUsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjoxNjI1LCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IllVUFJBREVWIiwibWUiOnsiaWQiOiIyMjY2MTQ0MDkzNDoyQHMud2hhdHNhcHAubmV0IiwibGlkIjoiNTk2MzIwNDczNzAyODA6MkBsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ05UcHo5OEVFS3FZK3NvR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6InFTNzNLTmhRbVpFbi9qaDNLY21KQ2xSUXNJTzRRRVZiZ2NEZWkzTDluVGs9IiwiYWNjb3VudFNpZ25hdHVyZSI6IjhPcXZTeCtWVTJPUyt4ejloT0VCNWVsbWJBaEZTQkNnbFNEMlM5MGdpQm9rZDZJOEtNNld6ckIxZHVYdVRkR3BXWk1IM3k1OGpkcTdxeFNWeDhENERRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJ2VDU2R21ja3kxWUQ2bnlDaXcyWVcwWE1IR2xvd2YrK09JcDBRTlcrMVA4Q3czSFNmMXhDYkwvT3N6TTY1ZXBwZFBiZ096ZDRITGI5YkcrR3p1elFEdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIyNjYxNDQwOTM0OjJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYWt1OXlqWVVKbVJKLzQ0ZHluSmlRcFVVTENEdUVCRlc0SEEzb3R5L1owNSJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FrSUF3Z1MifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzY3ODAzOTYwLCJsYXN0UHJvcEhhc2giOiJubTNCYiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTFFLIn0=",
AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN || "true",
AUTO_STATUS_REPLY: process.env.AUTO_STATUS_REPLY || "false",
AUTO_STATUS_REACT: process.env.AUTO_STATUS_REACT || "true",
AUTO_STATUS_MSG: process.env.AUTO_STATUS_MSG || "*SEEN YOUR STATUS BY DEATH-EMPEROR-MD 🤍*",
WELCOME: process.env.WELCOME || "true",
ADMIN_EVENTS: process.env.ADMIN_EVENTS || "false",
ANTI_LINK: process.env.ANTI_LINK || "true",
MENTION_REPLY: process.env.MENTION_REPLY || "false",
MENU_IMAGE_URL: process.env.MENU_IMAGE_URL || "https://files.catbox.moe/v9jd7w.jpg",
PREFIX: process.env.PREFIX || "+", 
BOT_NAME: process.env.BOT_NAME || "DEATH-EMPEROR-MD",
STICKER_NAME: process.env.STICKER_NAME || "DEATH-EMPEROR-MD",
CUSTOM_REACT: process.env.CUSTOM_REACT || "false", 
CUSTOM_REACT_EMOJIS: process.env.CUSTOM_REACT_EMOJIS || "💝,💖,💗,❤️‍🩹,❤️,🧡,💛,💚,💙,💜,🤎,🖤,🤍",
DELETE_LINKS: process.env.DELETE_LINKS || "false",
OWNER_NUMBER: process.env.OWNER_NUMBER || "2250546841168",
OWNER_NAME: process.env.OWNER_NAME || "DEATH EMPEROR",
DESCRIPTION: process.env.DESCRIPTION || "*© ᴘᴏᴡᴇʀᴇᴅ ʙʏ inconnu boy*",
ALIVE_IMG: process.env.ALIVE_IMG || "https://files.catbox.moe/v9jd7w.jpg",
LIVE_MSG: process.env.LIVE_MSG || ">*DEATH-EMPEROR-MD* 👸 ALIVE",
READ_MESSAGE: process.env.READ_MESSAGE || "false",
AUTO_REACT: process.env.AUTO_REACT || "false",
ANTI_BAD: process.env.ANTI_BAD || "false",
MODE: process.env.MODE || "public",
ANTI_LINK_KICK: process.env.ANTI_LINK_KICK || "false",
AUTO_VOICE: process.env.AUTO_VOICE || "false",
AUTO_STICKER: process.env.AUTO_STICKER || "false",
AUTO_REPLY: process.env.AUTO_REPLY || "false",
ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "false",
PUBLIC_MODE: process.env.PUBLIC_MODE || "true",
AUTO_TYPING: process.env.AUTO_TYPING || "false", 
READ_CMD: process.env.READ_CMD || "false",
DEV: process.env.DEV || "2250546841168",     
ANTI_VV: process.env.ANTI_VV || "true",
ANTI_DEL_PATH: process.env.ANTI_DEL_PATH || "log", 
AUTO_RECORDING: process.env.AUTO_RECORDING || "false"
};
  
